### ISSUE TITLE
Minimal kernel version ?

### ISSUE THREAD

**Issue by ffontaine** [a13xp0p0v/kernel-hardening-checker#106]
Hi, thanks for your great tool.
I'm wondering if there is a minimal kernel requirement for kernel-hardening-check?
Can I run it on any kernel configuration (e.g. on a kernel 4.1.x)?

**Comment by a13xp0p0v** [comment]
Hello @ffontaine,
Thanks for your kind words.
For sure, you can use `kernel-hardening-checker` for checking configuration of the old kernels.
Of course, some of the failing checks can't be resolved for old kernels because the recent security features haven't been backported to them.
