### ISSUE TITLE
Add io_uring_disabled sysctl to disable/limit io_uring creation

### ISSUE THREAD

**Issue by winterknife** [a13xp0p0v/kernel-hardening-checker#109]
Consider disabling IO_uring access using sysctl tunable apart from the `CONFIG_IO_URING` kconfig option that's already implemented.

More information here: [https://www.phoronix.com/news/Google-Restricting-IO_uring](https://www.phoronix.com/news/Google-Restricting-IO_uring)

[https://www.phoronix.com/news/Linux-6.6-sysctl-IO_uring](https://www.phoronix.com/news/Linux-6.6-sysctl-IO_uring)

**Comment by a13xp0p0v** [comment]
Closing as finished.
Thanks @Willenst.
