### ISSUE TITLE
Kernel Debug Metadata Access with CONFIG_DYNAMIC_DEBUG

### ISSUE THREAD

**Issue by wryMitts** [a13xp0p0v/kernel-hardening-checker#111]
Despite restricting access to kernel logs, it seems like this kernel debug log file is accessible with permissions `644` at `/proc/dynamic_debug/control`

It is listed to be located on DebugFS, although, it can also live in ProcFS, as it is on my system without DebugFS, per docs.

I also have `kernel.dmesg_restrict = 1` too. 

Maybe this is an oversight from kernel developers? I don't know. I don't see any memory addresses in mine, they seem to be removed, but this file still should probably not be readable by all users?

https://www.kernel.org/doc/html/v4.12/admin-guide/dynamic-debug-howto.html
https://cateee.net/lkddb/web-lkddb/DYNAMIC_DEBUG.html

**EDIT: I've realized this isn't necessarily a log file but still seems to be a little revealing. Feel free to close if this is out of scope, since this is more a job for distro to secure the file rather than Kernel.**

**Comment by a13xp0p0v** [comment]
Hello @wryMitts,
Thanks for creating the issue.
Unprivileged user can only read this file.
Do you see security-sensitive data in it?

**Comment by a13xp0p0v** [comment]
Thanks for the info, @wryMitts !
For now, closing the issue.
