### ISSUE TITLE
Linux 6.9 Renames Many CPU Mitigation CONFIGs to CONFIG_MITIGATION_...

### ISSUE THREAD

**Issue by wryMitts** [a13xp0p0v/kernel-hardening-checker#117]
Hello,

Looks like big change for naming schemes

Merged by Torvalds for 6.9

Many options will be renamed, for example:
```
x86/bugs: Rename CONFIG_RETHUNK              => CONFIG_MITIGATION_RETHUNK
  x86/bugs: Rename CONFIG_CPU_SRSO             => CONFIG_MITIGATION_SRSO
  x86/bugs: Rename CONFIG_CPU_IBRS_ENTRY       => CONFIG_MITIGATION_IBRS_ENTRY
  x86/bugs: Rename CONFIG_CPU_UNRET_ENTRY      => CONFIG_MITIGATION_UNRET_ENTRY
  x86/bugs: Rename CONFIG_SLS                  => CONFIG_MITIGATION_SLS
```
And several more in this commit below

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=685d98211273f60e38a6d361b62d7016c545297e

**Comment by jvoisin** [comment]
I think this issue can now be closed :)

**Comment by a13xp0p0v** [comment]
Implemented in:
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/9d1c4cf0068065842f838125245ead146bf247b6
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/86b67f39d3846fddb4419689c0e2d3ff35876cc5
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/78f559541028faaa02884f0fd9cc955fbbf4ca47

Closing.
Thanks!
