### ISSUE TITLE
The separation between desktop and server.

### ISSUE THREAD

**Issue by migrgh** [a13xp0p0v/kernel-hardening-checker#118]
Hello,

i would like to discuss the idea of implementing a separation between server and desktop.
There is separation between arch and show output.

- -m {verbose,json,show_ok,show_fail}, --mode {verbose,json,show_ok,show_fail}
- -p {X86_64,X86_32,ARM64,ARM}, --print {X86_64,X86_32,ARM64,ARM}

I have found the following obvious config that prevent booting a desktop.

- CONFIG_FB
- CONFIG_VT 
- CONFIG_KCMP # Selected by [y]: DRM [=y]

There are of course a few more, but they are not necessary for booting.
CONFIG_USE_NS # firefox / unprivileged container like systemd-nspawn

**Comment by migrgh** [comment]
current situation of automatic merging the Kconfig fragment you have to manual go over options like CONFIG_FB if in need.

or have a profile which work using automatic merging of the Kconfig fragment.

but yes it's very use case specific how a profile should look like.

**Comment by a13xp0p0v** [comment]
Hello @migrgh and @wryMitts,

Thanks for creating this issue. It is connected to the issue #50.

CC @petervanvugt, @egberts.

Please have a look and give your ideas.

What do you think about a mechanism allowing the `kernel-hardening-checker` users to create new custom checks and redefine the existing rules?

For example, `kernel-hardening-checker` may have a new `-r` argument for specifying a file with rule changes from the user.
