### ISSUE TITLE
Integration with oracle/kconfigs

### ISSUE THREAD

**Issue by evdenis** [a13xp0p0v/kernel-hardening-checker#119]
There is a collection of kconfigs which are automatically updated in https://github.com/oracle/kconfigs/tree/main/out
It looks possible to do the integration with the project instead to tracking distro configs in this project.

**Comment by a13xp0p0v** [comment]
@evdenis, thank you!

We can use these kconfig files in CI to check `kernel-hardening-checker` and reorganize the [kernel_hardening_checker/config_files](https://github.com/a13xp0p0v/kernel-hardening-checker/tree/master/kernel_hardening_checker/config_files) directory.

**Comment by evdenis** [comment]
https://blogs.oracle.com/linux/post/explore-linux-kernel-kconfigs

**Comment by a13xp0p0v** [comment]
Closing as done!
