### ISSUE TITLE
Disable `CONFIG_N_GSM`

### ISSUE THREAD

**Issue by cgzones** [a13xp0p0v/kernel-hardening-checker#122]
For attack surface reduction one might want to disable `CONFIG_N_GSM`.
See also: https://www.openwall.com/lists/oss-security/2024/04/17/1

**Comment by a13xp0p0v** [comment]
Hi @cgzones.
Thanks for the info.
It looks like the existing recommendation `sysctl dev.tty.ldisc_autoload = 0` solves this, doesn't it?

**Comment by a13xp0p0v** [comment]
Yes,  `sysctl dev.tty.ldisc_autoload = 0` is another solution.
But I added the `CONFIG_N_GSM` check anyway.
Thanks.
