### ISSUE TITLE
Which Python versions should `kernel-hardening-checker` support?

### ISSUE THREAD

**Issue by a13xp0p0v** [a13xp0p0v/kernel-hardening-checker#133]
The CI scripts of `kernel-hardening-checker` run on Python versions that are currently officially supported:
![CI](https://github.com/a13xp0p0v/kernel-hardening-checker/assets/1419667/4a628a03-f5ab-4aaf-9e14-0a75680616fa)
![Python versions](https://github.com/a13xp0p0v/kernel-hardening-checker/assets/1419667/66c799ce-ed19-4d68-90e8-636d686d4b89)
(from https://devguide.python.org/versions/)

**Question**
Should `kernel-hardening-checker` also work on some older Python versions?
Is it needed on old machines?
What do you think?

**Comment by jvoisin** [comment]
I don't think that kernel-hardening-checker depends on ultra-modern python features, so supporting old-ish-but-still-maintained python version shouldn't add any overhead.

**Comment by egberts** [comment]
`os.path` is going away soon.  `pathlib.Path` is the new "path"

**Comment by jvoisin** [comment]
`os.path` isn't going anywhere soon, according to the [documentation](https://docs.python.org/3/library/os.path.html)

**Comment by a13xp0p0v** [comment]
`from __future__ import annotations` is supported since Python 3.7.

**Comment by a13xp0p0v** [comment]
Assignment expression or "walrus operator” `NAME := expr` has been supported since Python 3.8.
It is used in `./kernel_hardening_checker/__init__.py`.

**Comment by a13xp0p0v** [comment]
Closing this question for now.
Supporting Python starting from v3.8 looks reasonable.
