### ISSUE TITLE
New kconfig SECURITY_PROC_MEM_RESTRICT_WRITES

### ISSUE THREAD

**Issue by osevan** [a13xp0p0v/kernel-hardening-checker#147]
The new SECURITY_PROC_MEM_RESTRICT_WRITES Kconfig option allows restricting writes to the mem file of processes unless the current process ptraces to that given task. 

https://lore.kernel.org/lkml/20240712-vfs-procfs-ce7e6c7cf26b@brauner/

**Comment by winterknife** [comment]
Another reference: https://www.phoronix.com/news/Linux-6.11-Tightens-Mem-Access

**Comment by a13xp0p0v** [comment]
@osevan, @winterknife, thanks for creating the issue!

Looks like the proposed version of this feature is not accepted:
https://lore.kernel.org/lkml/CAHk-=wiGWLChxYmUA5HrT5aopZrB7_2VTa0NLZcxORgkUe5tEQ@mail.gmail.com/

So let's wait and see.
Closing this issue for now.

**Comment by a13xp0p0v** [comment]
Implemented in https://github.com/a13xp0p0v/kernel-hardening-checker/pull/201.
Thanks!
