### ISSUE TITLE
Add kconfig option `CONFIG_CFI_AUTO_DEFAULT`

### ISSUE THREAD

**Issue by winterknife** [a13xp0p0v/kernel-hardening-checker#149]
This kconfig option is an alternative to the `cfi=kcfi` kernel command-line parameter check that's already implemented.

Reference: https://www.phoronix.com/news/Linux-6.11-Hardening

**Comment by flipthewho** [comment]
hello, @winterknife, @a13xp0p0v 
i implemented this ussue in my fork and merged all commits from test branch to release
now there is a #154 pull request into main repo

**Comment by a13xp0p0v** [comment]
Implemented by @flipthewho.
Closing.
