### ISSUE TITLE
LIST_HARDENED and DEBUG_LIST should be handled differently since the security properties are the same

### ISSUE THREAD

**Issue by thestinger** [a13xp0p0v/kernel-hardening-checker#166]
LIST_HARDENED exists as a higher performance alternative to DEBUG_LIST providing the same security benefits with lower performance cost. DEBUG_LIST selects LIST_HARDENED since it implies the security properties of LIST_HARDENED. If DEBUG_LIST is enabled, the LIST_HARDENED checks aren't actually used but rather are provided by DEBUG_LIST. Therefore, on recent kernels, you could simply check for LIST_HARDENED and ignore DEBUG_LIST but the script supports the LTS branches so that can't be done as a simplification yet.

The check should look for **either** DEBUG_LIST or LIST_HARDENED rather than checking for both. Older kernels don't have LIST_HARDENED but have the same security hardening available via DEBUG_LIST. Newer kernels can use LIST_HARDENED instead of DEBUG_LIST for the same security properties with lower overhead.

Also see https://x.com/grsecurity/status/1745862639362715988, grsecurity moved to this too.

cc @kees

**Comment by a13xp0p0v** [comment]
Thank you @thestinger.

Done in https://github.com/a13xp0p0v/kernel-hardening-checker/commit/24c1a906d96f77202837e90d4b1f9f5d9933e1b9.
