### ISSUE TITLE
CONFIG_AMD_IOMMU_V2 = m appears also to be correct

### ISSUE THREAD

**Issue by brandonweeks** [a13xp0p0v/kernel-hardening-checker#57]
```
CONFIG_AMD_IOMMU = y
CONFIG_AMD_IOMMU_V2 = m
```
appears to correctly setup the AMD v2 IOMMU on supported hardware (tested on NixOS) and is the config option used by [Fedora/RHEL](https://gitlab.com/cki-project/kernel-ark/-/blob/os-build/redhat/configs/common/generic/x86/x86_64/CONFIG_AMD_IOMMU_V2).

If you agree with this assessment, any pointers on how to add an OR to the existing AND conditional for `CONFIG_AMD_IOMMU`?

**Comment by a13xp0p0v** [comment]
Hello @brandonweeks 

Could you give any details on tests you mentioned?

Thanks!

**Comment by a13xp0p0v** [comment]
Closing for now.
Please reopen if needed.
Thanks!
