### ISSUE TITLE
Consider removing/not recommending CONFIG_ZERO_CALL_USED_REGS

### ISSUE THREAD

**Issue by jvoisin** [a13xp0p0v/kernel-hardening-checker#82]
CONFIG_ZERO_CALL_USED_REGS is [useless at best](https://dustri.org/b/paper-notes-clean-the-scratch-registers-a-way-to-mitigate-return-oriented-programming-attacks.html), with a **significant** performance impact.

This is a security theatre knob, and the performance budget would be better spent elsewhere.

**Comment by a13xp0p0v** [comment]
@jvoisin, thanks for the article!
It looks reasonable, we'll discuss it.
