### ISSUE TITLE
Add RDK Linux Hardening specification flags

### ISSUE THREAD

**Issue by frakman1** [a13xp0p0v/kernel-hardening-checker#84]
The [RDK Linux Hardening specification](https://developer.rdkcentral.com/documentation/documentation/licensee_specific_subsystems/rdk_security_concepts/rdk_software_security_specifications/rdk_linux_hardening_specification/) lists many flags that are not checked in this tool. The first five I looked for were not there: `CONFIG_DEBUG_KERNEL` `CONFIG_MARKERS` `CONFIG_DEBUG_MEMLEAK` and `CONFIG_ELF_CORE`

Perhaps these can be added as part of a new 'RDK security policy' check for the 'decision' column

**Comment by a13xp0p0v** [comment]
Need to compare these recommendations with the current `kernel-hardening-checker` rules.

Gonna do that after preparing the next release of the tool.

**Comment by a13xp0p0v** [comment]
I looked through these ideas.
Not all of them are about the kernel.

I've added the `CONFIG_CRASH_DUMP` check also recommended by ClipOS.

Thanks! Closing the issue.
