### ISSUE TITLE
Check for module force loading?

### ISSUE THREAD

**Issue by vobst** [a13xp0p0v/kernel-hardening-checker#95]
Would it make sense to check for `CONFIG_MODULE_FORCE_LOAD`? It could prevent attackers from loading slightly mismatching kernel modules. However, but it seems kind of redundant given that you already recommend disabling modules or enforcing signatures. Maybe it could be checked as a fall back if both stronger measures are disabled.

**Comment by a13xp0p0v** [comment]
Hello @vobst, thanks for the idea.

Added [e5f804e](https://github.com/a13xp0p0v/kernel-hardening-checker/commit/e5f804ede6ea7f66f674c2825396c15c216c718d).
