### ISSUE TITLE
new tag?

### ISSUE THREAD

**Issue by asarubbo** [a13xp0p0v/kernel-hardening-checker#96]
Hello @a13xp0p0v

[kernel-hardening-checker](https://github.com/a13xp0p0v/kernel-hardening-checker) it's really a great work!

I have recently added it into the [Gentoo tree](https://github.com/gentoo/gentoo/commit/151491904fa748c04cdff48a3884d52e18da9c0a) and I noticed that a lot of commits have been done after the last tag. Would you mind to issue a new minor release?
Thanks a lot

**Comment by a13xp0p0v** [comment]
Hello @asarubbo, thanks for kind words!

I'm currently preparing a new release of the tool.  A new tag will appear soon.

**Comment by a13xp0p0v** [comment]
Done!

The release [v0.6.6](https://github.com/a13xp0p0v/kernel-hardening-checker/releases/tag/v0.6.6) is published!
It corresponds to the Linux kernel 6.6.
